class LightroomCli < Formula
  include Language::Python::Virtualenv

  desc "CLI tool for Adobe Lightroom Classic — 107 commands for full Lightroom control"
  homepage "https://github.com/znznzna/lightroom-cli"
  url "https://github.com/znznzna/lightroom-cli/archive/refs/tags/v1.0.0.tar.gz"
  # sha256 will be filled after release
  license "MIT"
  head "https://github.com/znznzna/lightroom-cli.git", branch: "main"

  depends_on "python@3.12"

  # Resource blocks will be generated by `brew update-python-resources`
  # after the package is published to PyPI.
  # Example:
  # resource "click" do
  #   url "https://files.pythonhosted.org/packages/..."
  #   sha256 "..."
  # end

  def install
    virtualenv_install_with_resources
  end

  def post_install
    system bin/"lr", "plugin", "install", "--quiet"
  end

  def caveats
    <<~EOS
      Lightroom Classic must be running with the plugin active.

      To install/update the Lightroom plugin:
        lr plugin install

      To verify the connection:
        lr system check-connection
    EOS
  end

  test do
    assert_match "lr", shell_output("#{bin}/lr --version")
  end
end
